# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../gui/sftexternalwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_external_image_window(object):
    def setupUi(self, external_image_window):
        external_image_window.setObjectName("external_image_window")
        external_image_window.resize(800, 600)
        external_image_window.setFrameShape(QtWidgets.QFrame.StyledPanel)
        external_image_window.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chart_image_holder = QtWidgets.QLabel(external_image_window)
        self.chart_image_holder.setGeometry(QtCore.QRect(0, 0, 800, 551))
        self.chart_image_holder.setAlignment(QtCore.Qt.AlignCenter)
        self.chart_image_holder.setObjectName("chart_image_holder")
        self.close_external_window_btn = QtWidgets.QPushButton(external_image_window)
        self.close_external_window_btn.setGeometry(QtCore.QRect(330, 560, 141, 41))
        self.close_external_window_btn.setObjectName("close_external_window_btn")
        self.close_external_window_btn.clicked.connect(external_image_window.close)
        self.retranslateUi(external_image_window)
        QtCore.QMetaObject.connectSlotsByName(external_image_window)

    def retranslateUi(self, external_image_window):
        _translate = QtCore.QCoreApplication.translate
        external_image_window.setWindowTitle(_translate("external_image_window", "Frame"))
        self.chart_image_holder.setText(_translate("external_image_window", "TextLabel"))
        self.close_external_window_btn.setText(_translate("external_image_window", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    external_image_window = QtWidgets.QFrame()
    ui = Ui_external_image_window()
    ui.setupUi(external_image_window)
    external_image_window.show()
    sys.exit(app.exec_())
